# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: reddit_app
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: 
      name: ['ruby-full', 'ruby-dev', 'build-essential']
    # apt: "name={{ item }} state=present"
    # with_items:
    #   - ruby-full
    #   - ruby-dev
    #   - build-essential
      update_cache: yes

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: reddit_app
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D68FA50FEA312927
    
 # - name: Add repo
 #   shell: echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list

  # Add specified repository into sources list.
  - apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  
  - name: Install mongodb package
 #   debug:
 #     msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"
    apt:
      name: mongodb
      update_cache: yes

  - name: Start service mongodb if not started
    service:
      name: mongodb
      state: started


# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
 # - name: Remove me after adding real things
 #   debug:
 #     msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"

 # git clone
  - git: 
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit

  - name: Execute shell command
    shell:
      cmd: bundle install && puma -d
      chdir: ./reddit1
